github: [chris-short]
patreon: devopsish
custom: ["paypal.me/devopsish", devopsish.com, chrisshort.net, kubenews.net, kubernetesreadme.com, devopsreadme.com, devopsnewsletters.com, nomedium.dev, padbury.app, crashloopbackoff.dev]
